# Generated by Django 4.1.7 on 2023-04-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_leave_form_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancel', 'Cancel')], default='Pending', max_length=100),
        ),
    ]
