# Generated by Django 4.1.7 on 2023-04-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_form',
            name='number_of_days',
            field=models.CharField(default='', max_length=100),
        ),
    ]
