# Generated by Django 4.1.7 on 2023-04-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_leave_form_number_of_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='user',
        ),
        migrations.DeleteModel(
            name='Leave_form',
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
