# Generated by Django 4.1.7 on 2023-04-03 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_leave_form_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_form',
            name='id',
        ),
        migrations.AlterField(
            model_name='leave_form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
