# Generated by Django 4.1.7 on 2023-04-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0006_alter_leave_form_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reason', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'reason',
            },
        ),
    ]
